import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';

// The reset is limited to application objects; auth, storage and extensions stay intact.
export function buildDatabaseReset(schema, seed) {
    const tables = [...new Set([...schema.matchAll(/^create table (?:if not exists )?public\.([a-z_]+)\s*\(/gm)].map(match => match[1]))];
    const functions = [...new Set([...schema.matchAll(/^create (?:or replace )?function public\.([a-z_]+)\s*\(/gm)].map(match => match[1]))];
    if (!tables.includes('profiles') || !functions.includes('cleanup_expired_imported_events')) {
        throw new Error('The schema must include profiles and the final event expiry contract.');
    }
    // Flatten the historical migration transactions into one atomic installation.
    const installation = schema.replace(/^\s*(?:begin|commit);[ \t]*\r?$/gm, '');
    return `-- GENERATED by npm run db:reset:build. Deletes all Gacha Management data.\n` +
        `-- Run the entire file in the SQL Editor of the configured Supabase project.\n` +
        `begin;\n` +
        `do $reset$ declare fn record; begin\n` +
        `    for fn in select p.oid::regprocedure::text as signature from pg_proc p\n` +
        `        join pg_namespace n on n.oid = p.pronamespace\n` +
        `        where n.nspname = 'public' and p.proname in (${functions.map(name => `'${name}'`).join(', ')})\n` +
        `    loop execute 'drop function if exists ' || fn.signature || ' cascade'; end loop;\n` +
        `end $reset$;\n` +
        tables.map(name => `drop table if exists public.${name} cascade;`).join('\n') + '\n' +
        installation + '\n' + seed + `\nnotify pgrst, 'reload schema';\ncommit;\n`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    const root = new URL('../', import.meta.url);
    const output = new URL('.local-deliveries/profiles/reset-live.sql', root);
    const [schema, seed] = await Promise.all([
        readFile(new URL('db/schema.sql', root), 'utf8'), readFile(new URL('db/seed.sql', root), 'utf8'),
    ]);
    await mkdir(new URL('.', output), { recursive: true });
    await writeFile(output, buildDatabaseReset(schema, seed));
    console.log('Ready: .local-deliveries/profiles/reset-live.sql');
    console.log('Generation only; no connection to the live database was made.');
}
